name: Deploy to server

on:
  push:
    branches: [ main ]  # alebo master, podľa vašej hlavnej vetvy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Krok na prepis ciest
      - name: Replace paths
        run: |
          find . -type f -name "*.html" -exec sed -i 's|/online-tools/src|/srv/docker/goodboog.com/src|g' {} +
      
      # Následné kroky pre deploy na server
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/srv/docker/goodboog.com/src"
